name: "CI/CD Pipeline for Finsight Valuation Platform"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  terraform:
    name: "Terraform Plan & Apply"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/envs/dev

    steps:
      # 1. Checkout repository code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Authenticate to GCP using Workload Identity Federation (Keyless)
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/258838507488/locations/global/workloadIdentityPools/github-pool-dev/providers/github-provider-dev"
          service_account: "sa-terraform-dev@finsight-007.iam.gserviceaccount.com"

      # 3. Setup Terraform CLI on the runner
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      # 4. Initialize Terraform working directory
      - name: Terraform Init
        run: terraform init

      # 5. Generate execution plan for all PRs and pushes
      - name: Terraform Plan
        id: plan
        run: terraform plan -var-file="dev.tfvars" -no-color

      - name: Post Plan to PR
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        env:
          PLAN: "${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
            
            <details><summary>Show Plan Output</summary>
            
            \`\`\`terraform\n
            ${process.env.PLAN}
            \`\`\`
            
            </details>
            
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })  

      # 6. Apply changes ONLY when merged into main branch
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -var-file="dev.tfvars" -auto-approve -no-color